<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\bin\</OutputPath>
    <DocumentationFile>..\bin\RemoteViewing.XML</DocumentationFile> 
  </PropertyGroup>

</Project>
