<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>..\bin\</OutputPath>
    <DocumentationFile>..\bin\RemoteViewing.Windows.Forms.XML</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RemoteViewing\RemoteViewing.csproj" />
  </ItemGroup>

</Project>
